[project]
name = "smart_health"
version = "0.1.0"
description = "30-day readmission predictor"
readme = "README.md"
authors = [{name = "Your Name"}]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest", "streamlit", "uvicorn[standard]"]

[tool.setuptools]
packages = ["src"]
